### ISSUE TITLE
대기 중인 병원 리스트는 p 키를 누를 시에만 출력됩니다 <= 작동이 안되는것 같습니다

### ISSUE THREAD

**Issue by 38sun** [Queue-ri/Korea-Covid-19-Vaccine-Reservation#11]
안녕하세요
"대기 중인 병원 리스트는 p 키를 누를 시에만 출력됩니다 "
p키가 작동이 안되는것 같습니다
1.3 버전에서 작동되는것 확인했지만
그이후 버전에서는 p키가 안되는것 같습니다

**Comment by WAY2GOOD4U** [comment]
1.7 버전 현재 P 키 작동 잘 되고있습니다

**Comment by 38sun** [comment]
> 1.7 버전 현재 P 키 활발히 진행되고 있습니다

저는 테스트 해봐도 1.3 은 작동되는데 1.7은 안되고 있거든요.

**Comment by Queue-ri** [comment]
@38sun @WAY2GOOD4U 구버전은 사용하시면 안됩니다. **반드시 최신버전을 사용해주세요.**

오늘 hotfix 해서 latest가 v1.7a 로 올라갔습니다.
