### ISSUE TITLE
Connection Error 는 왜뜨는건가요?

### ISSUE THREAD

**Issue by mooooj** [Queue-ri/Korea-Covid-19-Vaccine-Reservation#12]
찾으시는 백신이 없거나 선착순 마감되었습니다.
Connection Error :  HTTPSConnectionPool(host='vaccine.kakao.com', port=443): Max retries exceeded with url: /api/v2/reservation (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002794F52C6A0>: Failed to establish a new connection: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다'))

검색을 하다 마지막부분에서 저런식으로 나오면서 프로그램이 종료됩니다.
1.7v Nuitka로 빌드했습니다 필터링은 사용하지 않았습니다

**Comment by Queue-ri** [comment]
인터넷 연결 문제인데 상당히 드문 일이고요 (저는 사용하면서 인터넷 선 빠진 적 외엔 한번도 못봤습니다.)
원인은 여러가지입니다.

현재 프로그램은 Timeout Error와 Connection Error가 발생해도 계속 돌아가도록 되어있습니다.
다만 Connection Error를 처리하는건 Read timed out의 특수한 케이스를 처리하기 위함이고, 다른 케이스는 발생 시 프로그램이 종료되므로 후자의 경우에 해당하시는 것 같네요.

안정적인 인터넷 환경에서 사용해주시고, 윈도우의 `네트워크 상태` - `프록시` - `자동으로 설정 검색` 이 켜져있다면 꺼주세요.

그리고 카카오 서버에 과부하 걸려서 끊긴 것일 수도 있습니다. 프로그램 한 개 돌렸다고 저렇게 안되는데 요즘 카카오 서버 상태가 안좋은 것 같네요.
