### ISSUE TITLE
안녕하세요 개발자님 질문 있습니다.

### ISSUE THREAD

**Issue by andy9072** [Queue-ri/Korea-Covid-19-Vaccine-Reservation#13]
개발자님이 주신 코딩 잘 받아서 돌리고 있었는데
아무리 몇시간을 돌려도 병원 찾으면
예약 시도한다는 이야기 나오다가
"찾으시는 백신이 없거나 선착순 마감되었습니다." 라는 문구만 뜨네요 ㅠㅠ
이건 제 집 와이파이 속도의 문제인 것일까요..? ㅜㅜ
초당 5,6 번 검색하는것 같은데 계속 선착순을 놓쳐서 혹시 뭐가 문제인지 알고 싶습니다
감사합니다.

**Comment by Queue-ri** [comment]
파일 버전명이 어떻게 되시나요?

그리고 5 ~ 6번이면 너무 느리네요. 속도 향상 버전이라 제 환경 기준 8 ~ 9번인데요.
컴퓨터 스펙이나 인터넷 속도 차이일 수도 있습니다.
@andy9072 님 환경에서 SJang1님 원본은 1초에 몇 번 조회하나요?

**Comment by andy9072** [comment]
지금은 AZ 백신 때문에 제대로 된 확인은 힘들지만 아마 이 버전보다는 느렸던것으로 기억해요. 그때도 모든 선착순을 놓쳤어요 ㅠㅠ 
제 환경 문제인것 같은데, (노트북에 와이파이입니다..)
피씨방 가서 하면 계정 보안? 이런 위험이 있을까요?

**Comment by Queue-ri** [comment]
끝날 때 카카오 로그아웃 하시면 별 문제 없을 듯 합니다. 그리고 대부분의 PC방은 롤백 시스템이 있어서..

다만 쓰시던 홈 환경이 아니니까 환경 차이에 따른 세팅이 더 필요할 수도 있어요.

참고로 `찾으시는 백신이 없거나 선착순 마감되었습니다.`는 잔여 물량이 발견되었으나 선택하신 백신이 아니어서 뜰 때도 있습니다.

AZ 병원들이 예약 시도에서 제외되는 경우는, 잔여 물량 수가 변하지 않을 때입니다.

다시 말해 잔여량이 변하면 다시 예약을 시도합니다. 실패하면 또 필터링하고요.

**Comment by Queue-ri** [comment]
그리고 지금 필터링 기능에 특정 케이스 버그가 확인되어서 v1.7b 릴리즈를 준비중입니다.

테스트 중인데 아스트라제네카 가져가는 사람이 없어서 컨펌이 안되네요.
테스트 완료되는대로 릴리즈 올라가니 예의주시해주세요.

**Comment by andy9072** [comment]
답변 감사합니다!

**Comment by andy9072** [comment]
아 그리고 제가 좌표값을 설정할때 구글 지도를 보고 했는데 혹시 이게 문제가 될 가능성이 있을까요??
카카오톡 지도를 이용해야 할까요??

**Comment by Queue-ri** [comment]
둘이 호환 안됩니다. **제 프로그램을 사용하실땐 반드시 제가 작성한 매뉴얼을 읽어주세요.**

[좌표값 찾는법](https://github.com/Queue-ri/Korea-Covid-19-Vaccine-Reservation/blob/main/docs/coords-manual.md)을 참고하시고, Issue는 원래 주제별로 따로 작성하는 공간입니다. 추가 질문은 별도의 Issue로 부탁드려요!

**Comment by andy9072** [comment]
앗 그랬군요. 그러겠습니닷!  감사합니다! 다시 해보겠습니다.
