### ISSUE TITLE
지도에서 범위 설정 할 때

### ISSUE THREAD

**Issue by andy9072** [Queue-ri/Korea-Covid-19-Vaccine-Reservation#14]
혹시 권장하는 검색 범위 정도가 있나요?
너무 넓은 범위를 선택해서 제 매크로 속도가 느린가 해서요.
예를 들어 강남구 전체를 설정하면 아무래도 느려지나요?
감사합니다.

**Comment by chaeun9811** [comment]
한개의 구 정도로는 넓은범위가 아닌것 같습니다 오히려 병원수가 많아야 잔여백신발생 수가 올라가고 신청할수있는 기회가 많아진다고 생각합니다 저는병원수가 100개에서 300개정도가 적당한것같습니다

**Comment by Queue-ri** [comment]
물론 이론 상 범위를 작게 잡으면 처리할 데이터가 줄어서 미세하게라도 빨라지는 건 맞는데, 그 정도 범위는 문제 없습니다.

저의 경우 강남 + 강북일부 + 서초일부 + 송파일부로 그것보다 더 넓은 범위였습니다.

성능을 최대로 사용하고 싶으시다면 다음 사항을 점검해주세요.
- **반드시 `nuitka`로 빌드**
- 최신 버전 사용 (현 기준 v1.7b)
- `잔여백신이 있는 병원만 조회` 옵션 선택
- 카톡, 크롬의 불필요한 탭 등 필요없는 프로세스 정리

그 외는 컴퓨터 자체의 스펙, 인터넷 속도에 크게 영향을 받습니다.

[이전 답변](https://github.com/Queue-ri/Korea-Covid-19-Vaccine-Reservation/issues/13#issuecomment-895748692)에서 말씀드린 제 환경에서의 성능도 질문자분처럼 노트북 + 와이파이 조합이였습니다.

**Comment by andy9072** [comment]
두 분 다 답변 정말 감사드립니다!! 
제가 놓친건지 속도에 문제가 있는것인지..
매크로로 잔여백신 예약에 성공하면 국민비서 구삐한테 휴대폰으로 카톡이 오지요??
혹시 이미 잡았는데 그 순간 컴퓨터를 안봐서 놓쳤나 해서요 ㅠㅜ

**Comment by Queue-ri** [comment]
@andy9072 상단의 답변이 수정되었습니다.

`잔여백신이 있는 병원만 조회` 옵션을 선택하시면 더 빠릅니다.

현재 핫타임이라 환경 최적화하고 해당 옵션 선택하셔야 평소의 퍼포먼스가 나올 겁니다.

예약에 성공하면 카카오톡 지갑 알림 및 국민비서 문자가 옵니다. 또는 병원에서 바로 전화하기도 하니 핸드폰을 곁에 두셔야 합니다.
