### ISSUE TITLE
카카오 사용자 정보를 불러올 수 없는 문제

### ISSUE THREAD

**Issue by shinwr** [Queue-ri/Korea-Covid-19-Vaccine-Reservation#15]
크롬 설정도 맞추고 알림 신청도 했는데 에러 검출 페이지에서 에러가 뜨고, 사용자 정보를 못 불러오는 이유는 무엇일까요?
그 전에는 잘 작동했었는데, 이상합니다

**Comment by Queue-ri** [comment]
오늘(8월 20일) 자정에 카카오에서 API 방식을 업데이트하여 사용자 정보를 못 불러오고 있습니다.

해당 issue는 테스트 후 fix 될 예정이며, 차후 경과를 알려드리겠습니다.

**Comment by Queue-ri** [comment]
해당 문제를 패치한 [v1.8](https://github.com/Queue-ri/Korea-Covid-19-Vaccine-Reservation/releases/tag/v1.8) 이 release 되었습니다.

[카카오 사용자 쿠키 찾는법](https://github.com/Queue-ri/Korea-Covid-19-Vaccine-Reservation/blob/main/docs/cookie-manual.md)을 참고하여 쿠키 값을 수동으로 파싱하신 후, 해당 값을 프로그램에 입력하시면 카카오 계정이 연동됩니다.

당장은 계정 연동법이 번거로우나 차후 개선의 여지가 있으면 또 업데이트 할 예정입니다.

감사합니다.
