### ISSUE TITLE
카카오톡 백신 예약 문제발생!

### ISSUE THREAD

**Issue by mingyuu99** [Queue-ri/Korea-Covid-19-Vaccine-Reservation#3]
pc로는 지원하지 않는 접근이라면서 모든 항목 클릭이 안됩니다! 모바일로만 가능토록 바뀐듯 하네요

**Comment by Queue-ri** [comment]
어디서 발생한 문제인지 자세한 설명 부탁드립니다.

카카오 백신 맵이라면 방금 정상 작동하는 것을 확인했습니다.
카카오 백신 맵에서 지원하지 않는 환경이라고 뜨는 것은 프로그램 작동에 영향을 미치지 않습니다.

**Comment by JunJun0411** [comment]
https://vaccine.kakao.com/api/v1/user 를 막아둔거같아요

**Comment by JunJun0411** [comment]
https://vaccine.kakao.com/api/v1/user  웹으로 들어가면 정보가 있는데 
requests할 때 {'error': 'error occurred'} 로 뜹니다.
