### ISSUE TITLE
좌표값이 뭘 말하시는 건가요?

### ISSUE THREAD

**Issue by Jaeyeop-Jung** [Queue-ri/Korea-Covid-19-Vaccine-Reservation#5]
개발자모드 - network에서 좌표값을 찾으라고 하셨는데 자세히 말씀해주실 수 있나요? 

혹시 콘솔에 
var x, y; document.onmousemove=(e)=>{x=e.pageX;y=e.pageY;}
console.log(x, y);
이 명령어로 마우스 좌표를 말씀하시는건지..

**Comment by Queue-ri** [comment]
좌표값은 `left_count_by_coords` 의 request payload에 있습니다.

세부사항은 [좌표값 찾는법](https://github.com/Queue-ri/Korea-Covid-19-Vaccine-Reservation/blob/main/docs/coords-manual.md)을 참고해주세요.
