### ISSUE TITLE
계속 사용자 정보를 불러오는데 실패했다고 뜹니다

### ISSUE THREAD

**Issue by shinwr** [Queue-ri/Korea-Covid-19-Vaccine-Reservation#6]
계속 사용자 정보를 불러오는데 실패했다고 뜹니다
왜그런걸까요? ㅠㅠ
저번에 SangJ 님 꺼에서 그런 적 있었을 때 cookie.ini를 지우라고 했었던 것 같은데, 어떻게 지우는건지 모르겠습니다

**Comment by Queue-ri** [comment]
`cookie.ini`는 사용자 편의상 들어갔던 기능입니다.

제껀 `cookie.ini`를 사용하지 않고 그 이전처럼 항상 기본 경로를 따릅니다. (v1.6 부턴 기본이 아닌 프로파일도 지원합니다.)

[로그인 매뉴얼](https://github.com/Queue-ri/Korea-Covid-19-Vaccine-Reservation/blob/main/docs/login-manual.md) 참고하시고 다시 확인해보세요.
