### ISSUE TITLE
AZ 백신물량

### ISSUE THREAD

**Issue by chaeun9811** [Queue-ri/Korea-Covid-19-Vaccine-Reservation#7]
AZ 잔여백신이 너무많아서 다른병원들도 인식하지만 이때 request 를 0으로 두면 계정이 정지당할 위험성이 커지나요? Discussion 탭이없어서 이슈로 남겨봅니다

**Comment by Queue-ri** [comment]
@chaeun9811 request 를 0으로 둔다는게 어떤 걸 말씀하시는 건가요?

그리고 제껀 자꾸 아스트라제네카를 인식해서 선착순 마감이라고 떠도 무시하셔도 됩니다.
일단 잔여 백신이 있는 병원들에는 모두 한번씩 설정한 백신으로 예약을 시도해보고, 안되면 다시 조회하도록 로직이 수정되어있기 때문입니다.

**Comment by chaeun9811** [comment]
답변감사합니다 잘사용하겠습니다

**Comment by chaeun9811** [comment]
지금AZ가 병원들에 많아서 그런데 한번에 여러병원들에 신청을하게되어도 계정에 큰위험이없을까요??

**Comment by Queue-ri** [comment]
혹시 사용중이신 `config.ini` 파일을 qriositylog@gmail.com 으로 보내주실 수 있나요?
AZ가 다수 나오는 환경에서 테스트해보고, 다음 업데이트때 이런 상황을 대비해서 새 기능을 추가하려고 합니다.

제 개인적인 생각으로는 당장 문제는 없을 것 같습니다만.. 이건 솔직히 카카오가 얼마만큼 강경하게 나오느냐의 문제라서 확신해드릴 수는 없습니다.

**Comment by chaeun9811** [comment]
범위가 그렇게 넓은편이 아니지만 어느정도 AZ가 있습니다 메일보내드렸습니다

**Comment by Queue-ri** [comment]
Commit 7a2c61d was dropped due to a wrong issue reference. (#7 -> #9)

Please refer to 08f6bfa instead.
