### ISSUE TITLE
다운로드 파일 어디서 받나요 ㅠㅠ

### ISSUE THREAD

**Issue by syj3206** [Queue-ri/Korea-Covid-19-Vaccine-Reservation#8]
어떤걸 받아야하는지 모르겠어요..

**Comment by Queue-ri** [comment]
[Release](https://github.com/Queue-ri/Korea-Covid-19-Vaccine-Reservation/releases)에서 `zip` 파일 다운받으시고

[빌드 방법](https://github.com/Queue-ri/Korea-Covid-19-Vaccine-Reservation/blob/main/docs/build-manual.md)을 참고하여 `cb.py`를 빌드하시면 실행 파일이 만들어집니다.

**Comment by syj3206** [comment]
감사합니다 zip 파일 받았는데 빌드가 무엇인가요 ??

**Comment by syj3206** [comment]
조금만 더 자세히 알려주실 수 있나요?

**Comment by Queue-ri** [comment]
[빌드 방법](https://github.com/Queue-ri/Korea-Covid-19-Vaccine-Reservation/blob/main/docs/build-manual.md)에 나온 명령어가 빌드 명령어입니다.

다운받으신 zip을 압축 해제하고 해당 폴더 경로에서 빌드 명령어를 입력하시면 `cb.exe`가 생성됩니다. (윈도우 기준, macOS는 `cb`)

그냥 `cb.py` 그대로 실행하실 수도 있지만 그건 성능이 100% 나오지 않아서
성능을 추구하는 제 프로젝트 특성 상 권장드리진 않습니다.

**Comment by syj3206** [comment]
감사합니다!! 파이썬 처음 써봐서 낑낑대다가 성공했어요 ㅎㅎ

**Comment by syj3206** [comment]
혹시 창 두개로 돌려도 괜찮을까요?

**Comment by Queue-ri** [comment]
저때는 가능했는데 지금은 모르겠습니다.
오늘 AZ가 대량 풀려서 자꾸 필요 이상의 request를 쏘니 같은 병원들이 자꾸 걸린다면 하나만 돌리시길 권장드릴게요.
이 문제는 다음 업데이트에서 개선할 예정입니다.

**Comment by syj3206** [comment]
![제목 없음](https://user-images.githubusercontent.com/88520587/128673856-451780e3-21e7-4baf-9562-127940a6a0c3.png)
갑자기 이렇게 뜨네요 무슨 문제일까요?

**Comment by Queue-ri** [comment]
해당 사진만으로는 정상 작동인지 무슨 문제가 있는지 알 수 없습니다.
그리고 이 프로그램은 개조한거라 기존 원본 프로젝트와 동일하지 않아요. 제 입맛대로 고치거든요.
그래서 원본의 사용설명서대로 사용하시면 안됩니다.

`README.md`를 참고하시고 issue는 주제 별로 따로 작성해주세요. 감사합니다.
