### ISSUE TITLE
잔여백신 신청 오류

### ISSUE THREAD

**Issue by chaeun9811** [Queue-ri/Korea-Covid-19-Vaccine-Reservation#9]
x이비인후과의원 에서 백신을 2개 발견했습니다.
VEN00013 으로 예약을 시도합니다.
잔여백신 접종 신청이 선착순 마감되었습니다.
검색 완료: 2021-08-09 15:57:45.135409

x이비인후과의원 에서 백신을 2개 발견했습니다.
VEN00013 으로 예약을 시도합니다.
잔여백신 접종 신청이 선착순 마감되었습니다.
검색 완료: 2021-08-09 15:57:47.767900

x이비인후과의원 에서 백신을 2개 발견했습니다.
VEN00013 으로 예약을 시도합니다.
잔여백신 접종 신청이 선착순 마감되었습니다.
검색 완료: 2021-08-09 15:57:49.343894

x이비인후과의원 에서 백신을 2개 발견했습니다.
VEN00013 으로 예약을 시도합니다.
잔여백신 접종 신청이 선착순 마감되었습니다.
검색 완료: 2021-08-09 15:57:55.361904

x이비인후과의원 에서 백신을 2개 발견했습니다.
VEN00013 으로 예약을 시도합니다.
잔여백신 접종 신청이 선착순 마감되었습니다.
검색 완료: 2021-08-09 15:57:55.361904

x이비인후과의원 에서 백신을 2개 발견했습니다.
VEN00013 으로 예약을 시도합니다.
잔여백신 접종 신청이 선착순 마감되었습니다.
검색 완료: 2021-08-09 15:57:55.361904

(임의로 병원이름을 x 라고 칭하였습니다)

오늘 3시57분정도에 네이버톡톡으로 x이비인후과의원에서 ven00013 (화이자) 잔여백신이 확인되었습니다 
카카오에서 발견은 잘하는데 신청이 제대로 이루어지고있는것같지않습니다 확인부탁드립니다

**Comment by chaeun9811** [comment]
https://github.com/SJang1/korea-covid-19-remaining-vaccine-macro/issues/980#issue-963774690
아마 이 문제와 관련이 있어보입니다

**Comment by Queue-ri** [comment]
로그 마지막에 `검색 완료: 2021-08-09 15:57:55.361904`가 3개 중복인 것은 붙여넣다가 중복되신 것 같습니다.

예약이 안되는 것은 다음의 경우를 생각해볼 수 있습니다.
1. 다른 사람이 먼저 예약했을 경우
2. 카카오에서 매크로 패턴을 감지하여 예약을 차단했을 경우
3. 일시적인 카카오 서버 오류
4. 프로그램 자체의 버그

4번은 가능성이 거의 없고요, 1번으로 추정 중입니다.
로그의 시간 간격을 보니 오늘 AZ 때문에 쓸데없는 예약 시도가 많아져서 성능이 10배 이상으로 저하되었는데, 저정도 딜레이라면 충분히 예약이 늦을 수 있습니다.

현재 성능 저하 문제는 [v1.7 Release](https://github.com/Queue-ri/Korea-Covid-19-Vaccine-Reservation/releases/tag/v1.7)에서 **필터링 모드**로 패치한 상태입니다. [보내주신 `config.ini`](https://github.com/Queue-ri/Korea-Covid-19-Vaccine-Reservation/issues/7#issuecomment-894949974)로 테스트를 완료했지만 사용하시면서 버그가 있을 경우 제보 부탁드립니다.

또한 `pyinstaller`가 아닌 **`nuitka`로 빌드**해주시고,
**카카오톡이나 크롬의 불필요한 탭을 전부 정리**하신 후에 사용하셔야 최적의 성능이 나오니 참고해주세요.

추가로 현재 2, 3번일 수도 있겠다는 미심쩍은 부분이 있어 내일 급하게 v1.7a 버전을 릴리즈할 수도 있습니다.
이 Issue는 아직 조사중이므로 Close 하지 말아주세요.

**Comment by Queue-ri** [comment]
3번의 문제가 있는 것으로 확인되어 [v1.7a](https://github.com/Queue-ri/Korea-Covid-19-Vaccine-Reservation/releases/tag/v1.7a) 가 릴리즈되었습니다. **반드시 긴급 패치된 버전을 사용해주세요.**

추가적인 문제는 별도의 Issue로 작성해주시기 바랍니다. 감사합니다.

**Comment by chaeun9811** [comment]
정상작동 확인했습니다 감사합니다!

**Comment by Queue-ri** [comment]
@chaeun9811 혹시 예약 성공하셨나요?

**Comment by chaeun9811** [comment]
@Queue-ri  네 화이자 정상적으로 성공했습니다

**Comment by Queue-ri** [comment]
@chaeun9811 알려주셔서 감사합니다! 😊
